/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PowerImport } from './routes/power'
import { Route as ItemsImport } from './routes/items'
import { Route as IndexImport } from './routes/index'
import { Route as PowerGeneratorsGeneratorIdImport } from './routes/power/generators.$generatorId'
import { Route as ItemsItemIdRecipeTypeRecipeTypeImport } from './routes/items.$itemId.recipeType/$recipeType'
import { Route as ItemsItemIdRecipeTypeRecipeTypeRecipesRecipeIdImport } from './routes/items.$itemId.recipeType/$recipeType/recipes.$recipeId'

// Create/Update Routes

const PowerRoute = PowerImport.update({
  id: '/power',
  path: '/power',
  getParentRoute: () => rootRoute,
} as any)

const ItemsRoute = ItemsImport.update({
  id: '/items',
  path: '/items',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const PowerGeneratorsGeneratorIdRoute = PowerGeneratorsGeneratorIdImport.update(
  {
    id: '/generators/$generatorId',
    path: '/generators/$generatorId',
    getParentRoute: () => PowerRoute,
  } as any,
)

const ItemsItemIdRecipeTypeRecipeTypeRoute =
  ItemsItemIdRecipeTypeRecipeTypeImport.update({
    id: '/$itemId/recipeType/$recipeType',
    path: '/$itemId/recipeType/$recipeType',
    getParentRoute: () => ItemsRoute,
  } as any)

const ItemsItemIdRecipeTypeRecipeTypeRecipesRecipeIdRoute =
  ItemsItemIdRecipeTypeRecipeTypeRecipesRecipeIdImport.update({
    id: '/recipes/$recipeId',
    path: '/recipes/$recipeId',
    getParentRoute: () => ItemsItemIdRecipeTypeRecipeTypeRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/items': {
      id: '/items'
      path: '/items'
      fullPath: '/items'
      preLoaderRoute: typeof ItemsImport
      parentRoute: typeof rootRoute
    }
    '/power': {
      id: '/power'
      path: '/power'
      fullPath: '/power'
      preLoaderRoute: typeof PowerImport
      parentRoute: typeof rootRoute
    }
    '/power/generators/$generatorId': {
      id: '/power/generators/$generatorId'
      path: '/generators/$generatorId'
      fullPath: '/power/generators/$generatorId'
      preLoaderRoute: typeof PowerGeneratorsGeneratorIdImport
      parentRoute: typeof PowerImport
    }
    '/items/$itemId/recipeType/$recipeType': {
      id: '/items/$itemId/recipeType/$recipeType'
      path: '/$itemId/recipeType/$recipeType'
      fullPath: '/items/$itemId/recipeType/$recipeType'
      preLoaderRoute: typeof ItemsItemIdRecipeTypeRecipeTypeImport
      parentRoute: typeof ItemsImport
    }
    '/items/$itemId/recipeType/$recipeType/recipes/$recipeId': {
      id: '/items/$itemId/recipeType/$recipeType/recipes/$recipeId'
      path: '/recipes/$recipeId'
      fullPath: '/items/$itemId/recipeType/$recipeType/recipes/$recipeId'
      preLoaderRoute: typeof ItemsItemIdRecipeTypeRecipeTypeRecipesRecipeIdImport
      parentRoute: typeof ItemsItemIdRecipeTypeRecipeTypeImport
    }
  }
}

// Create and export the route tree

interface ItemsItemIdRecipeTypeRecipeTypeRouteChildren {
  ItemsItemIdRecipeTypeRecipeTypeRecipesRecipeIdRoute: typeof ItemsItemIdRecipeTypeRecipeTypeRecipesRecipeIdRoute
}

const ItemsItemIdRecipeTypeRecipeTypeRouteChildren: ItemsItemIdRecipeTypeRecipeTypeRouteChildren =
  {
    ItemsItemIdRecipeTypeRecipeTypeRecipesRecipeIdRoute:
      ItemsItemIdRecipeTypeRecipeTypeRecipesRecipeIdRoute,
  }

const ItemsItemIdRecipeTypeRecipeTypeRouteWithChildren =
  ItemsItemIdRecipeTypeRecipeTypeRoute._addFileChildren(
    ItemsItemIdRecipeTypeRecipeTypeRouteChildren,
  )

interface ItemsRouteChildren {
  ItemsItemIdRecipeTypeRecipeTypeRoute: typeof ItemsItemIdRecipeTypeRecipeTypeRouteWithChildren
}

const ItemsRouteChildren: ItemsRouteChildren = {
  ItemsItemIdRecipeTypeRecipeTypeRoute:
    ItemsItemIdRecipeTypeRecipeTypeRouteWithChildren,
}

const ItemsRouteWithChildren = ItemsRoute._addFileChildren(ItemsRouteChildren)

interface PowerRouteChildren {
  PowerGeneratorsGeneratorIdRoute: typeof PowerGeneratorsGeneratorIdRoute
}

const PowerRouteChildren: PowerRouteChildren = {
  PowerGeneratorsGeneratorIdRoute: PowerGeneratorsGeneratorIdRoute,
}

const PowerRouteWithChildren = PowerRoute._addFileChildren(PowerRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/items': typeof ItemsRouteWithChildren
  '/power': typeof PowerRouteWithChildren
  '/power/generators/$generatorId': typeof PowerGeneratorsGeneratorIdRoute
  '/items/$itemId/recipeType/$recipeType': typeof ItemsItemIdRecipeTypeRecipeTypeRouteWithChildren
  '/items/$itemId/recipeType/$recipeType/recipes/$recipeId': typeof ItemsItemIdRecipeTypeRecipeTypeRecipesRecipeIdRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/items': typeof ItemsRouteWithChildren
  '/power': typeof PowerRouteWithChildren
  '/power/generators/$generatorId': typeof PowerGeneratorsGeneratorIdRoute
  '/items/$itemId/recipeType/$recipeType': typeof ItemsItemIdRecipeTypeRecipeTypeRouteWithChildren
  '/items/$itemId/recipeType/$recipeType/recipes/$recipeId': typeof ItemsItemIdRecipeTypeRecipeTypeRecipesRecipeIdRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/items': typeof ItemsRouteWithChildren
  '/power': typeof PowerRouteWithChildren
  '/power/generators/$generatorId': typeof PowerGeneratorsGeneratorIdRoute
  '/items/$itemId/recipeType/$recipeType': typeof ItemsItemIdRecipeTypeRecipeTypeRouteWithChildren
  '/items/$itemId/recipeType/$recipeType/recipes/$recipeId': typeof ItemsItemIdRecipeTypeRecipeTypeRecipesRecipeIdRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/items'
    | '/power'
    | '/power/generators/$generatorId'
    | '/items/$itemId/recipeType/$recipeType'
    | '/items/$itemId/recipeType/$recipeType/recipes/$recipeId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/items'
    | '/power'
    | '/power/generators/$generatorId'
    | '/items/$itemId/recipeType/$recipeType'
    | '/items/$itemId/recipeType/$recipeType/recipes/$recipeId'
  id:
    | '__root__'
    | '/'
    | '/items'
    | '/power'
    | '/power/generators/$generatorId'
    | '/items/$itemId/recipeType/$recipeType'
    | '/items/$itemId/recipeType/$recipeType/recipes/$recipeId'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ItemsRoute: typeof ItemsRouteWithChildren
  PowerRoute: typeof PowerRouteWithChildren
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ItemsRoute: ItemsRouteWithChildren,
  PowerRoute: PowerRouteWithChildren,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/items",
        "/power"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/items": {
      "filePath": "items.tsx",
      "children": [
        "/items/$itemId/recipeType/$recipeType"
      ]
    },
    "/power": {
      "filePath": "power.tsx",
      "children": [
        "/power/generators/$generatorId"
      ]
    },
    "/power/generators/$generatorId": {
      "filePath": "power/generators.$generatorId.tsx",
      "parent": "/power"
    },
    "/items/$itemId/recipeType/$recipeType": {
      "filePath": "items.$itemId.recipeType/$recipeType.tsx",
      "parent": "/items",
      "children": [
        "/items/$itemId/recipeType/$recipeType/recipes/$recipeId"
      ]
    },
    "/items/$itemId/recipeType/$recipeType/recipes/$recipeId": {
      "filePath": "items.$itemId.recipeType/$recipeType/recipes.$recipeId.tsx",
      "parent": "/items/$itemId/recipeType/$recipeType"
    }
  }
}
ROUTE_MANIFEST_END */
